/* @flow */
// Test is to make sure that something is not renamed twice (e.g. require > _7 > _2)
// which used to happen one of the variable names generated by prepack already
// existed in the orinal file.

function require() {
  return {};
}

var _7 = {
  foo: " hello ",
};

var _a = {
  factory: {},
};
var _8 = {
  foo: {},
  "1": _a,
};

var modules = _8;

function f() {
  var x = _7.foo === " hello " && modules.foo === undefined && require().bar === " goodbye";
  return x;
}

function _d() {
  return f();
}

inspect = _d;
