// flow-typed signature: 91253616435274658664be70a5673e3c
// flow-typed version: <<STUB>>/babel-helper-get-function-arity_v^6.8.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-helper-get-function-arity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-helper-get-function-arity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-helper-get-function-arity/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-helper-get-function-arity/lib/index.js' {
  declare module.exports: $Exports<'babel-helper-get-function-arity/lib/index'>;
}
