// flow-typed signature: fe7e54a98300f409fd3c32a79a2e317f
// flow-typed version: <<STUB>>/babel-plugin-jest-hoist_v^23.2.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-jest-hoist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-jest-hoist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-jest-hoist/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-jest-hoist/build/index.js' {
  declare module.exports: $Exports<'babel-plugin-jest-hoist/build/index'>;
}
