// flow-typed signature: 00b8ab338c10ac6b548eacb2b78c1d81
// flow-typed version: <<STUB>>/babel-helper-function-name_v^6.8.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-helper-function-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-helper-function-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-helper-function-name/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-helper-function-name/lib/index.js' {
  declare module.exports: $Exports<'babel-helper-function-name/lib/index'>;
}
