// flow-typed signature: f887f8e4d8a4093cf25d353f6e88a62a
// flow-typed version: <<STUB>>/base62_v^1.1.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base62'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'base62' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'base62/base62' {
  declare module.exports: any;
}

declare module 'base62/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'base62/base62.js' {
  declare module.exports: $Exports<'base62/base62'>;
}
declare module 'base62/test/test.js' {
  declare module.exports: $Exports<'base62/test/test'>;
}
