// flow-typed signature: 4cb0251c6b76a7114e3fcf5df235a05d
// flow-typed version: <<STUB>>/eslint-config-kittens_v^1.0.5/flow_v0.25.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-kittens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-kittens' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-kittens/index' {
  declare module.exports: $Exports<'eslint-config-kittens'>;
}
declare module 'eslint-config-kittens/index.js' {
  declare module.exports: $Exports<'eslint-config-kittens'>;
}
