// flow-typed signature: ae49f73baa6e38423f28cfaa56cde4b6
// flow-typed version: <<STUB>>/eslint-plugin-header_v^1.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-header'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-header' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-header/lib/comment-parser' {
  declare module.exports: any;
}

declare module 'eslint-plugin-header/lib/rules/header' {
  declare module.exports: any;
}

declare module 'eslint-plugin-header/tests/lib/comment-parser-test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-header/tests/lib/rules/header' {
  declare module.exports: any;
}

declare module 'eslint-plugin-header/tests/support/block' {
  declare module.exports: any;
}

declare module 'eslint-plugin-header/tests/support/line' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-header/index' {
  declare module.exports: $Exports<'eslint-plugin-header'>;
}
declare module 'eslint-plugin-header/index.js' {
  declare module.exports: $Exports<'eslint-plugin-header'>;
}
declare module 'eslint-plugin-header/lib/comment-parser.js' {
  declare module.exports: $Exports<'eslint-plugin-header/lib/comment-parser'>;
}
declare module 'eslint-plugin-header/lib/rules/header.js' {
  declare module.exports: $Exports<'eslint-plugin-header/lib/rules/header'>;
}
declare module 'eslint-plugin-header/tests/lib/comment-parser-test.js' {
  declare module.exports: $Exports<'eslint-plugin-header/tests/lib/comment-parser-test'>;
}
declare module 'eslint-plugin-header/tests/lib/rules/header.js' {
  declare module.exports: $Exports<'eslint-plugin-header/tests/lib/rules/header'>;
}
declare module 'eslint-plugin-header/tests/support/block.js' {
  declare module.exports: $Exports<'eslint-plugin-header/tests/support/block'>;
}
declare module 'eslint-plugin-header/tests/support/line.js' {
  declare module.exports: $Exports<'eslint-plugin-header/tests/support/line'>;
}
