// flow-typed signature: 691184973888acc24da609e46f85c0c9
// flow-typed version: <<STUB>>/madge_v^1.6.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'madge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'madge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'madge/bin/cli' {
  declare module.exports: any;
}

declare module 'madge/lib/api' {
  declare module.exports: any;
}

declare module 'madge/lib/cyclic' {
  declare module.exports: any;
}

declare module 'madge/lib/graph' {
  declare module.exports: any;
}

declare module 'madge/lib/log' {
  declare module.exports: any;
}

declare module 'madge/lib/output' {
  declare module.exports: any;
}

declare module 'madge/lib/tree' {
  declare module.exports: any;
}

// Filename aliases
declare module 'madge/bin/cli.js' {
  declare module.exports: $Exports<'madge/bin/cli'>;
}
declare module 'madge/lib/api.js' {
  declare module.exports: $Exports<'madge/lib/api'>;
}
declare module 'madge/lib/cyclic.js' {
  declare module.exports: $Exports<'madge/lib/cyclic'>;
}
declare module 'madge/lib/graph.js' {
  declare module.exports: $Exports<'madge/lib/graph'>;
}
declare module 'madge/lib/log.js' {
  declare module.exports: $Exports<'madge/lib/log'>;
}
declare module 'madge/lib/output.js' {
  declare module.exports: $Exports<'madge/lib/output'>;
}
declare module 'madge/lib/tree.js' {
  declare module.exports: $Exports<'madge/lib/tree'>;
}
