// flow-typed signature: 32d4e4a79ef4ec16683f87120b5178b5
// flow-typed version: <<STUB>>/queue-fifo_v^0.2.3/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'queue-fifo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'queue-fifo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'queue-fifo/gulpfile' {
  declare module.exports: any;
}

declare module 'queue-fifo/test/queue-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'queue-fifo/gulpfile.js' {
  declare module.exports: $Exports<'queue-fifo/gulpfile'>;
}
declare module 'queue-fifo/index' {
  declare module.exports: $Exports<'queue-fifo'>;
}
declare module 'queue-fifo/index.js' {
  declare module.exports: $Exports<'queue-fifo'>;
}
declare module 'queue-fifo/test/queue-test.js' {
  declare module.exports: $Exports<'queue-fifo/test/queue-test'>;
}
