// flow-typed signature: 8c6ca2ba2615a25ac1e943c7cffaca9d
// flow-typed version: <<STUB>>/repeating_v^2.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'repeating'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'repeating' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'repeating/index' {
  declare module.exports: $Exports<'repeating'>;
}
declare module 'repeating/index.js' {
  declare module.exports: $Exports<'repeating'>;
}
