// flow-typed signature: 9376a5dd476c84a27a9865d751aaf7fa
// flow-typed version: <<STUB>>/seedrandom_v^2.4.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'seedrandom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'seedrandom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'seedrandom/Gruntfile' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/alea' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/alea.min' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/crypto' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/tychei' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/tychei.min' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/xor128' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/xor128.min' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/xor4096' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/xor4096.min' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/xorshift7' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/xorshift7.min' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/xorwow' {
  declare module.exports: any;
}

declare module 'seedrandom/lib/xorwow.min' {
  declare module.exports: any;
}

declare module 'seedrandom/seedrandom' {
  declare module.exports: any;
}

declare module 'seedrandom/seedrandom.min' {
  declare module.exports: any;
}

declare module 'seedrandom/test/bitgen' {
  declare module.exports: any;
}

declare module 'seedrandom/test/browserified' {
  declare module.exports: any;
}

declare module 'seedrandom/test/cryptotest' {
  declare module.exports: any;
}

declare module 'seedrandom/test/lib/qunit' {
  declare module.exports: any;
}

declare module 'seedrandom/test/lib/require' {
  declare module.exports: any;
}

declare module 'seedrandom/test/nodetest' {
  declare module.exports: any;
}

declare module 'seedrandom/test/prngtest' {
  declare module.exports: any;
}

declare module 'seedrandom/test/qunitassert' {
  declare module.exports: any;
}

// Filename aliases
declare module 'seedrandom/Gruntfile.js' {
  declare module.exports: $Exports<'seedrandom/Gruntfile'>;
}
declare module 'seedrandom/index' {
  declare module.exports: $Exports<'seedrandom'>;
}
declare module 'seedrandom/index.js' {
  declare module.exports: $Exports<'seedrandom'>;
}
declare module 'seedrandom/lib/alea.js' {
  declare module.exports: $Exports<'seedrandom/lib/alea'>;
}
declare module 'seedrandom/lib/alea.min.js' {
  declare module.exports: $Exports<'seedrandom/lib/alea.min'>;
}
declare module 'seedrandom/lib/crypto.js' {
  declare module.exports: $Exports<'seedrandom/lib/crypto'>;
}
declare module 'seedrandom/lib/tychei.js' {
  declare module.exports: $Exports<'seedrandom/lib/tychei'>;
}
declare module 'seedrandom/lib/tychei.min.js' {
  declare module.exports: $Exports<'seedrandom/lib/tychei.min'>;
}
declare module 'seedrandom/lib/xor128.js' {
  declare module.exports: $Exports<'seedrandom/lib/xor128'>;
}
declare module 'seedrandom/lib/xor128.min.js' {
  declare module.exports: $Exports<'seedrandom/lib/xor128.min'>;
}
declare module 'seedrandom/lib/xor4096.js' {
  declare module.exports: $Exports<'seedrandom/lib/xor4096'>;
}
declare module 'seedrandom/lib/xor4096.min.js' {
  declare module.exports: $Exports<'seedrandom/lib/xor4096.min'>;
}
declare module 'seedrandom/lib/xorshift7.js' {
  declare module.exports: $Exports<'seedrandom/lib/xorshift7'>;
}
declare module 'seedrandom/lib/xorshift7.min.js' {
  declare module.exports: $Exports<'seedrandom/lib/xorshift7.min'>;
}
declare module 'seedrandom/lib/xorwow.js' {
  declare module.exports: $Exports<'seedrandom/lib/xorwow'>;
}
declare module 'seedrandom/lib/xorwow.min.js' {
  declare module.exports: $Exports<'seedrandom/lib/xorwow.min'>;
}
declare module 'seedrandom/seedrandom.js' {
  declare module.exports: $Exports<'seedrandom/seedrandom'>;
}
declare module 'seedrandom/seedrandom.min.js' {
  declare module.exports: $Exports<'seedrandom/seedrandom.min'>;
}
declare module 'seedrandom/test/bitgen.js' {
  declare module.exports: $Exports<'seedrandom/test/bitgen'>;
}
declare module 'seedrandom/test/browserified.js' {
  declare module.exports: $Exports<'seedrandom/test/browserified'>;
}
declare module 'seedrandom/test/cryptotest.js' {
  declare module.exports: $Exports<'seedrandom/test/cryptotest'>;
}
declare module 'seedrandom/test/lib/qunit.js' {
  declare module.exports: $Exports<'seedrandom/test/lib/qunit'>;
}
declare module 'seedrandom/test/lib/require.js' {
  declare module.exports: $Exports<'seedrandom/test/lib/require'>;
}
declare module 'seedrandom/test/nodetest.js' {
  declare module.exports: $Exports<'seedrandom/test/nodetest'>;
}
declare module 'seedrandom/test/prngtest.js' {
  declare module.exports: $Exports<'seedrandom/test/prngtest'>;
}
declare module 'seedrandom/test/qunitassert.js' {
  declare module.exports: $Exports<'seedrandom/test/qunitassert'>;
}
