// flow-typed signature: 860492a8fda59a3f14c96d9e845c5d80
// flow-typed version: <<STUB>>/test262-integrator_v^1.2.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'test262-integrator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'test262-integrator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'test262-integrator/lib/index' {
  declare module.exports: any;
}

declare module 'test262-integrator/lib/report' {
  declare module.exports: any;
}

// Filename aliases
declare module 'test262-integrator/index' {
  declare module.exports: $Exports<'test262-integrator'>;
}
declare module 'test262-integrator/index.js' {
  declare module.exports: $Exports<'test262-integrator'>;
}
declare module 'test262-integrator/lib/index.js' {
  declare module.exports: $Exports<'test262-integrator/lib/index'>;
}
declare module 'test262-integrator/lib/report.js' {
  declare module.exports: $Exports<'test262-integrator/lib/report'>;
}
