// flow-typed signature: f0996c4a08f76e6b3408912bda3f3ece
// flow-typed version: <<STUB>>/v8-profiler_v5.7.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'v8-profiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'v8-profiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'v8-profiler/tools/annotate-tag' {
  declare module.exports: any;
}

declare module 'v8-profiler/tools/commit-changes' {
  declare module.exports: any;
}

declare module 'v8-profiler/tools/exec' {
  declare module.exports: any;
}

declare module 'v8-profiler/tools/history' {
  declare module.exports: any;
}

declare module 'v8-profiler/tools/NODE_NEXT' {
  declare module.exports: any;
}

declare module 'v8-profiler/tools/prepublish-to-npm' {
  declare module.exports: any;
}

declare module 'v8-profiler/tools/publish-to-npm' {
  declare module.exports: any;
}

declare module 'v8-profiler/tools/push-to-githab' {
  declare module.exports: any;
}

declare module 'v8-profiler/tools/release' {
  declare module.exports: any;
}

declare module 'v8-profiler/tools/update-changelog' {
  declare module.exports: any;
}

declare module 'v8-profiler/tools/update-npm-version' {
  declare module.exports: any;
}

declare module 'v8-profiler/v8-profiler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'v8-profiler/tools/annotate-tag.js' {
  declare module.exports: $Exports<'v8-profiler/tools/annotate-tag'>;
}
declare module 'v8-profiler/tools/commit-changes.js' {
  declare module.exports: $Exports<'v8-profiler/tools/commit-changes'>;
}
declare module 'v8-profiler/tools/exec.js' {
  declare module.exports: $Exports<'v8-profiler/tools/exec'>;
}
declare module 'v8-profiler/tools/history.js' {
  declare module.exports: $Exports<'v8-profiler/tools/history'>;
}
declare module 'v8-profiler/tools/NODE_NEXT.js' {
  declare module.exports: $Exports<'v8-profiler/tools/NODE_NEXT'>;
}
declare module 'v8-profiler/tools/prepublish-to-npm.js' {
  declare module.exports: $Exports<'v8-profiler/tools/prepublish-to-npm'>;
}
declare module 'v8-profiler/tools/publish-to-npm.js' {
  declare module.exports: $Exports<'v8-profiler/tools/publish-to-npm'>;
}
declare module 'v8-profiler/tools/push-to-githab.js' {
  declare module.exports: $Exports<'v8-profiler/tools/push-to-githab'>;
}
declare module 'v8-profiler/tools/release.js' {
  declare module.exports: $Exports<'v8-profiler/tools/release'>;
}
declare module 'v8-profiler/tools/update-changelog.js' {
  declare module.exports: $Exports<'v8-profiler/tools/update-changelog'>;
}
declare module 'v8-profiler/tools/update-npm-version.js' {
  declare module.exports: $Exports<'v8-profiler/tools/update-npm-version'>;
}
declare module 'v8-profiler/v8-profiler.js' {
  declare module.exports: $Exports<'v8-profiler/v8-profiler'>;
}
