// flow-typed signature: 157088d679e8cd26f71af29e6bfa3ccc
// flow-typed version: <<STUB>>/v8-profiler-node8_v6.0.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'v8-profiler-node8'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'v8-profiler-node8' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'v8-profiler-node8/tools/annotate-tag' {
  declare module.exports: any;
}

declare module 'v8-profiler-node8/tools/commit-changes' {
  declare module.exports: any;
}

declare module 'v8-profiler-node8/tools/exec' {
  declare module.exports: any;
}

declare module 'v8-profiler-node8/tools/history' {
  declare module.exports: any;
}

declare module 'v8-profiler-node8/tools/NODE_NEXT' {
  declare module.exports: any;
}

declare module 'v8-profiler-node8/tools/prepublish-to-npm' {
  declare module.exports: any;
}

declare module 'v8-profiler-node8/tools/publish-to-npm' {
  declare module.exports: any;
}

declare module 'v8-profiler-node8/tools/push-to-githab' {
  declare module.exports: any;
}

declare module 'v8-profiler-node8/tools/release' {
  declare module.exports: any;
}

declare module 'v8-profiler-node8/tools/update-changelog' {
  declare module.exports: any;
}

declare module 'v8-profiler-node8/tools/update-npm-version' {
  declare module.exports: any;
}

declare module 'v8-profiler-node8/v8-profiler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'v8-profiler-node8/tools/annotate-tag.js' {
  declare module.exports: $Exports<'v8-profiler-node8/tools/annotate-tag'>;
}
declare module 'v8-profiler-node8/tools/commit-changes.js' {
  declare module.exports: $Exports<'v8-profiler-node8/tools/commit-changes'>;
}
declare module 'v8-profiler-node8/tools/exec.js' {
  declare module.exports: $Exports<'v8-profiler-node8/tools/exec'>;
}
declare module 'v8-profiler-node8/tools/history.js' {
  declare module.exports: $Exports<'v8-profiler-node8/tools/history'>;
}
declare module 'v8-profiler-node8/tools/NODE_NEXT.js' {
  declare module.exports: $Exports<'v8-profiler-node8/tools/NODE_NEXT'>;
}
declare module 'v8-profiler-node8/tools/prepublish-to-npm.js' {
  declare module.exports: $Exports<'v8-profiler-node8/tools/prepublish-to-npm'>;
}
declare module 'v8-profiler-node8/tools/publish-to-npm.js' {
  declare module.exports: $Exports<'v8-profiler-node8/tools/publish-to-npm'>;
}
declare module 'v8-profiler-node8/tools/push-to-githab.js' {
  declare module.exports: $Exports<'v8-profiler-node8/tools/push-to-githab'>;
}
declare module 'v8-profiler-node8/tools/release.js' {
  declare module.exports: $Exports<'v8-profiler-node8/tools/release'>;
}
declare module 'v8-profiler-node8/tools/update-changelog.js' {
  declare module.exports: $Exports<'v8-profiler-node8/tools/update-changelog'>;
}
declare module 'v8-profiler-node8/tools/update-npm-version.js' {
  declare module.exports: $Exports<'v8-profiler-node8/tools/update-npm-version'>;
}
declare module 'v8-profiler-node8/v8-profiler.js' {
  declare module.exports: $Exports<'v8-profiler-node8/v8-profiler'>;
}
