// flow-typed signature: c3d699d8e0136301c17d450964419f5f
// flow-typed version: <<STUB>>/vscode-debugprotocol_v^1.24.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-debugprotocol'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-debugprotocol' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-debugprotocol/lib/debugProtocol' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-debugprotocol/lib/debugProtocol.js' {
  declare module.exports: $Exports<'vscode-debugprotocol/lib/debugProtocol'>;
}
