// flow-typed signature: b0105a82001632c14dcbf5fe23739b80
// flow-typed version: <<STUB>>/vscode-debugadapter_v^1.24.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-debugadapter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-debugadapter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-debugadapter/lib/debugSession' {
  declare module.exports: any;
}

declare module 'vscode-debugadapter/lib/handles' {
  declare module.exports: any;
}

declare module 'vscode-debugadapter/lib/logger' {
  declare module.exports: any;
}

declare module 'vscode-debugadapter/lib/loggingDebugSession' {
  declare module.exports: any;
}

declare module 'vscode-debugadapter/lib/main' {
  declare module.exports: any;
}

declare module 'vscode-debugadapter/lib/messages' {
  declare module.exports: any;
}

declare module 'vscode-debugadapter/lib/protocol' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-debugadapter/lib/debugSession.js' {
  declare module.exports: $Exports<'vscode-debugadapter/lib/debugSession'>;
}
declare module 'vscode-debugadapter/lib/handles.js' {
  declare module.exports: $Exports<'vscode-debugadapter/lib/handles'>;
}
declare module 'vscode-debugadapter/lib/logger.js' {
  declare module.exports: $Exports<'vscode-debugadapter/lib/logger'>;
}
declare module 'vscode-debugadapter/lib/loggingDebugSession.js' {
  declare module.exports: $Exports<'vscode-debugadapter/lib/loggingDebugSession'>;
}
declare module 'vscode-debugadapter/lib/main.js' {
  declare module.exports: $Exports<'vscode-debugadapter/lib/main'>;
}
declare module 'vscode-debugadapter/lib/messages.js' {
  declare module.exports: $Exports<'vscode-debugadapter/lib/messages'>;
}
declare module 'vscode-debugadapter/lib/protocol.js' {
  declare module.exports: $Exports<'vscode-debugadapter/lib/protocol'>;
}
