// flow-typed signature: 6b3104f896ee95abdc8475a4079566eb
// flow-typed version: <<STUB>>/vscode-debugprotocol_vx.x.x/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-debugprotocol'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-debugprotocol' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-debugprotocol/lib/debugProtocol' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-debugprotocol/lib/debugProtocol.js' {
  declare module.exports: $Exports<'vscode-debugprotocol/lib/debugProtocol'>;
}
