// flow-typed signature: 9611b8636a77cb4c887f9f1155bda121
// flow-typed version: <<STUB>>/webpack-cli_v^2.0.10/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-cli/bin/config-yargs' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/convert-argv' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/errorHelpers' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/prepareOptions' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/process-options' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/webpack' {
  declare module.exports: any;
}

declare module 'webpack-cli/commitlint.config' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/commands/add' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/commands/init' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/commands/make' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/commands/migrate' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/commands/remove' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/commands/serve' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/commands/update' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generate-loader/index' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generate-plugin/index' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generators/add-generator' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generators/init-generator' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generators/loader-generator' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generators/plugin-generator' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generators/remove-generator' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generators/update-generator' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generators/utils/entry' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generators/utils/module' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generators/utils/plugins' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generators/utils/tooltip' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generators/utils/validate' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/generators/webpack-generator' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/index' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/context/context' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/devServer/devServer' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/devtool/devtool' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/entry/entry' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/externals/externals' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/index' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/mode/mode' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/module/module' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/node/node' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/other/amd' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/other/bail' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/other/cache' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/other/merge' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/other/parallelism' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/other/profile' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/other/recordsInputPath' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/other/recordsOutputPath' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/other/recordsPath' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/output/output' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/performance/performance' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/plugins/plugins' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/resolve/resolve' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/resolveLoader/resolveLoader' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/stats/stats' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/target/target' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/top-scope/top-scope' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/watch/watch' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/init/transformations/watch/watchOptions' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/migrate/bannerPlugin/bannerPlugin' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/migrate/extractTextPlugin/extractTextPlugin' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/migrate/index' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/migrate/loaderOptionsPlugin/loaderOptionsPlugin' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/migrate/loaders/loaders' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/migrate/outputPath/outputPath' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/migrate/removeDeprecatedPlugins/removeDeprecatedPlugins' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/migrate/removeJsonLoader/removeJsonLoader' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/migrate/resolve/resolve' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/migrate/uglifyJsPlugin/uglifyJsPlugin' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/ast-utils' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/copy-utils' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/defineTest' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/hashtable' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/modify-config-helper' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/npm-exists' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/npm-packages-exists' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/package-manager' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/prop-types' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/resolve-packages' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/run-prettier' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-cli/bin/config-yargs.js' {
  declare module.exports: $Exports<'webpack-cli/bin/config-yargs'>;
}
declare module 'webpack-cli/bin/convert-argv.js' {
  declare module.exports: $Exports<'webpack-cli/bin/convert-argv'>;
}
declare module 'webpack-cli/bin/errorHelpers.js' {
  declare module.exports: $Exports<'webpack-cli/bin/errorHelpers'>;
}
declare module 'webpack-cli/bin/prepareOptions.js' {
  declare module.exports: $Exports<'webpack-cli/bin/prepareOptions'>;
}
declare module 'webpack-cli/bin/process-options.js' {
  declare module.exports: $Exports<'webpack-cli/bin/process-options'>;
}
declare module 'webpack-cli/bin/webpack.js' {
  declare module.exports: $Exports<'webpack-cli/bin/webpack'>;
}
declare module 'webpack-cli/commitlint.config.js' {
  declare module.exports: $Exports<'webpack-cli/commitlint.config'>;
}
declare module 'webpack-cli/lib/commands/add.js' {
  declare module.exports: $Exports<'webpack-cli/lib/commands/add'>;
}
declare module 'webpack-cli/lib/commands/init.js' {
  declare module.exports: $Exports<'webpack-cli/lib/commands/init'>;
}
declare module 'webpack-cli/lib/commands/make.js' {
  declare module.exports: $Exports<'webpack-cli/lib/commands/make'>;
}
declare module 'webpack-cli/lib/commands/migrate.js' {
  declare module.exports: $Exports<'webpack-cli/lib/commands/migrate'>;
}
declare module 'webpack-cli/lib/commands/remove.js' {
  declare module.exports: $Exports<'webpack-cli/lib/commands/remove'>;
}
declare module 'webpack-cli/lib/commands/serve.js' {
  declare module.exports: $Exports<'webpack-cli/lib/commands/serve'>;
}
declare module 'webpack-cli/lib/commands/update.js' {
  declare module.exports: $Exports<'webpack-cli/lib/commands/update'>;
}
declare module 'webpack-cli/lib/generate-loader/index.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generate-loader/index'>;
}
declare module 'webpack-cli/lib/generate-plugin/index.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generate-plugin/index'>;
}
declare module 'webpack-cli/lib/generators/add-generator.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generators/add-generator'>;
}
declare module 'webpack-cli/lib/generators/init-generator.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generators/init-generator'>;
}
declare module 'webpack-cli/lib/generators/loader-generator.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generators/loader-generator'>;
}
declare module 'webpack-cli/lib/generators/plugin-generator.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generators/plugin-generator'>;
}
declare module 'webpack-cli/lib/generators/remove-generator.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generators/remove-generator'>;
}
declare module 'webpack-cli/lib/generators/update-generator.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generators/update-generator'>;
}
declare module 'webpack-cli/lib/generators/utils/entry.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generators/utils/entry'>;
}
declare module 'webpack-cli/lib/generators/utils/module.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generators/utils/module'>;
}
declare module 'webpack-cli/lib/generators/utils/plugins.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generators/utils/plugins'>;
}
declare module 'webpack-cli/lib/generators/utils/tooltip.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generators/utils/tooltip'>;
}
declare module 'webpack-cli/lib/generators/utils/validate.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generators/utils/validate'>;
}
declare module 'webpack-cli/lib/generators/webpack-generator.js' {
  declare module.exports: $Exports<'webpack-cli/lib/generators/webpack-generator'>;
}
declare module 'webpack-cli/lib/index.js' {
  declare module.exports: $Exports<'webpack-cli/lib/index'>;
}
declare module 'webpack-cli/lib/init/index.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/index'>;
}
declare module 'webpack-cli/lib/init/transformations/context/context.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/context/context'>;
}
declare module 'webpack-cli/lib/init/transformations/devServer/devServer.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/devServer/devServer'>;
}
declare module 'webpack-cli/lib/init/transformations/devtool/devtool.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/devtool/devtool'>;
}
declare module 'webpack-cli/lib/init/transformations/entry/entry.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/entry/entry'>;
}
declare module 'webpack-cli/lib/init/transformations/externals/externals.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/externals/externals'>;
}
declare module 'webpack-cli/lib/init/transformations/index.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/index'>;
}
declare module 'webpack-cli/lib/init/transformations/mode/mode.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/mode/mode'>;
}
declare module 'webpack-cli/lib/init/transformations/module/module.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/module/module'>;
}
declare module 'webpack-cli/lib/init/transformations/node/node.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/node/node'>;
}
declare module 'webpack-cli/lib/init/transformations/other/amd.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/other/amd'>;
}
declare module 'webpack-cli/lib/init/transformations/other/bail.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/other/bail'>;
}
declare module 'webpack-cli/lib/init/transformations/other/cache.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/other/cache'>;
}
declare module 'webpack-cli/lib/init/transformations/other/merge.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/other/merge'>;
}
declare module 'webpack-cli/lib/init/transformations/other/parallelism.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/other/parallelism'>;
}
declare module 'webpack-cli/lib/init/transformations/other/profile.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/other/profile'>;
}
declare module 'webpack-cli/lib/init/transformations/other/recordsInputPath.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/other/recordsInputPath'>;
}
declare module 'webpack-cli/lib/init/transformations/other/recordsOutputPath.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/other/recordsOutputPath'>;
}
declare module 'webpack-cli/lib/init/transformations/other/recordsPath.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/other/recordsPath'>;
}
declare module 'webpack-cli/lib/init/transformations/output/output.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/output/output'>;
}
declare module 'webpack-cli/lib/init/transformations/performance/performance.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/performance/performance'>;
}
declare module 'webpack-cli/lib/init/transformations/plugins/plugins.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/plugins/plugins'>;
}
declare module 'webpack-cli/lib/init/transformations/resolve/resolve.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/resolve/resolve'>;
}
declare module 'webpack-cli/lib/init/transformations/resolveLoader/resolveLoader.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/resolveLoader/resolveLoader'>;
}
declare module 'webpack-cli/lib/init/transformations/stats/stats.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/stats/stats'>;
}
declare module 'webpack-cli/lib/init/transformations/target/target.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/target/target'>;
}
declare module 'webpack-cli/lib/init/transformations/top-scope/top-scope.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/top-scope/top-scope'>;
}
declare module 'webpack-cli/lib/init/transformations/watch/watch.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/watch/watch'>;
}
declare module 'webpack-cli/lib/init/transformations/watch/watchOptions.js' {
  declare module.exports: $Exports<'webpack-cli/lib/init/transformations/watch/watchOptions'>;
}
declare module 'webpack-cli/lib/migrate/bannerPlugin/bannerPlugin.js' {
  declare module.exports: $Exports<'webpack-cli/lib/migrate/bannerPlugin/bannerPlugin'>;
}
declare module 'webpack-cli/lib/migrate/extractTextPlugin/extractTextPlugin.js' {
  declare module.exports: $Exports<'webpack-cli/lib/migrate/extractTextPlugin/extractTextPlugin'>;
}
declare module 'webpack-cli/lib/migrate/index.js' {
  declare module.exports: $Exports<'webpack-cli/lib/migrate/index'>;
}
declare module 'webpack-cli/lib/migrate/loaderOptionsPlugin/loaderOptionsPlugin.js' {
  declare module.exports: $Exports<'webpack-cli/lib/migrate/loaderOptionsPlugin/loaderOptionsPlugin'>;
}
declare module 'webpack-cli/lib/migrate/loaders/loaders.js' {
  declare module.exports: $Exports<'webpack-cli/lib/migrate/loaders/loaders'>;
}
declare module 'webpack-cli/lib/migrate/outputPath/outputPath.js' {
  declare module.exports: $Exports<'webpack-cli/lib/migrate/outputPath/outputPath'>;
}
declare module 'webpack-cli/lib/migrate/removeDeprecatedPlugins/removeDeprecatedPlugins.js' {
  declare module.exports: $Exports<'webpack-cli/lib/migrate/removeDeprecatedPlugins/removeDeprecatedPlugins'>;
}
declare module 'webpack-cli/lib/migrate/removeJsonLoader/removeJsonLoader.js' {
  declare module.exports: $Exports<'webpack-cli/lib/migrate/removeJsonLoader/removeJsonLoader'>;
}
declare module 'webpack-cli/lib/migrate/resolve/resolve.js' {
  declare module.exports: $Exports<'webpack-cli/lib/migrate/resolve/resolve'>;
}
declare module 'webpack-cli/lib/migrate/uglifyJsPlugin/uglifyJsPlugin.js' {
  declare module.exports: $Exports<'webpack-cli/lib/migrate/uglifyJsPlugin/uglifyJsPlugin'>;
}
declare module 'webpack-cli/lib/utils/ast-utils.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/ast-utils'>;
}
declare module 'webpack-cli/lib/utils/copy-utils.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/copy-utils'>;
}
declare module 'webpack-cli/lib/utils/defineTest.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/defineTest'>;
}
declare module 'webpack-cli/lib/utils/hashtable.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/hashtable'>;
}
declare module 'webpack-cli/lib/utils/modify-config-helper.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/modify-config-helper'>;
}
declare module 'webpack-cli/lib/utils/npm-exists.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/npm-exists'>;
}
declare module 'webpack-cli/lib/utils/npm-packages-exists.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/npm-packages-exists'>;
}
declare module 'webpack-cli/lib/utils/package-manager.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/package-manager'>;
}
declare module 'webpack-cli/lib/utils/prop-types.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/prop-types'>;
}
declare module 'webpack-cli/lib/utils/resolve-packages.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/resolve-packages'>;
}
declare module 'webpack-cli/lib/utils/run-prettier.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/run-prettier'>;
}
