// flow-typed signature: 1f224679c72df69bc1a83214bdcd84b3
// flow-typed version: <<STUB>>/@babel/parser_v^7.0.0-beta.53/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/parser/bin/babel-parser' {
  declare module.exports: any;
}

declare module '@babel/parser/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/parser/bin/babel-parser.js' {
  declare module.exports: $Exports<'@babel/parser/bin/babel-parser'>;
}
declare module '@babel/parser/lib/index.js' {
  declare module.exports: $Exports<'@babel/parser/lib/index'>;
}
