// flow-typed signature: c0525799a7f3fe4fa2f7f8222226590d
// flow-typed version: <<STUB>>/@babel/plugin-proposal-export-default-from_v^7.0.0-beta.53/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-export-default-from'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-export-default-from' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-export-default-from/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-export-default-from/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-export-default-from/lib/index'>;
}
