// flow-typed signature: b5676378d55f7376bc725520ab242644
// flow-typed version: <<STUB>>/@babel/template_v^7.0.0-beta.53/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/template'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/template' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/template/lib/builder' {
  declare module.exports: any;
}

declare module '@babel/template/lib/formatters' {
  declare module.exports: any;
}

declare module '@babel/template/lib/index' {
  declare module.exports: any;
}

declare module '@babel/template/lib/literal' {
  declare module.exports: any;
}

declare module '@babel/template/lib/options' {
  declare module.exports: any;
}

declare module '@babel/template/lib/parse' {
  declare module.exports: any;
}

declare module '@babel/template/lib/populate' {
  declare module.exports: any;
}

declare module '@babel/template/lib/string' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/template/lib/builder.js' {
  declare module.exports: $Exports<'@babel/template/lib/builder'>;
}
declare module '@babel/template/lib/formatters.js' {
  declare module.exports: $Exports<'@babel/template/lib/formatters'>;
}
declare module '@babel/template/lib/index.js' {
  declare module.exports: $Exports<'@babel/template/lib/index'>;
}
declare module '@babel/template/lib/literal.js' {
  declare module.exports: $Exports<'@babel/template/lib/literal'>;
}
declare module '@babel/template/lib/options.js' {
  declare module.exports: $Exports<'@babel/template/lib/options'>;
}
declare module '@babel/template/lib/parse.js' {
  declare module.exports: $Exports<'@babel/template/lib/parse'>;
}
declare module '@babel/template/lib/populate.js' {
  declare module.exports: $Exports<'@babel/template/lib/populate'>;
}
declare module '@babel/template/lib/string.js' {
  declare module.exports: $Exports<'@babel/template/lib/string'>;
}
